### ISSUE TITLE
Multiple cognate sets with similar names, differing in numeric suffix

### ISSUE THREAD

**Issue by shash42** [lexibank/robinsonap#9]
I wanted to know the distinction between the multiple cognate sets with similar names like: 41_burdenstick-0, 41_burdenstick-1, 41_burdenstick-3... 

Is it correct to combine all these into a single cognate set? If not, why?

**Comment by chrzyki** [comment]
Hi, thanks for the question! If you have a look at the original/raw data (https://github.com/lexibank/robinsonap/blob/master/raw/AP_lexicon_coded.txt), the authors already supplied the information which lexemes are cognates and which aren't.

As such, the numerical suffix indicates a group membership (i.e. `teiwa-257_short-1-1` and `westernpantar-257_short-1-1` both share the cognate set ID `257_short-0`, thereby marking the lexemes as cognate). So no, lumping them together would make you lose information on cognate relationships.

**Comment by LinguList** [comment]
The "similar" names are a mere device for making IDs here. As the authors defined cognates within the same concept slot only, we use the concept-identifier (which is an ID itself) as part of the cognate set ID here. So they look similar but should be kept distinct.

**Comment by shash42** [comment]
Understood, thanks a lot for the prompt response!
